---
title: Good programming practices
author: Stat 251
categories:
- slides
- Week07
engine: knitr
format:
  revealjs:
    navigation-mode: vertical
    logo: N.svg
    theme: inverse.scss
    includes:
      in_header: header.html
date: '2026-02-24'
---

# Where we are

Homework 5 - graphics:

  - graded with feedback
  - grades not as high as I would like them ... check the feedback carefully!
  
Resubmissions for homeworks 1-5  open until the week after Spring Break

# Homework Submissions

- Render your file before the final submission

- and READ over it

- Make sure to
    
    - avoid lengthy output (like showing the full data set)
    
    - fix any errors and warnings
    
    - read the output ... e.g. 489 years of data (data manip homework) doesn't make sense

    - not install packages in the quarto document (rely on the user to figure out installations)
    - not call `View` (opens separate window during render)


# Homework #6

- relatively short - pay attention to details!

- one (unintentional) trap: `co2` object exists in R - leads to extremely strange numbers


# Homework 6

```{=html}
<iframe width="100%" height = "500px" src="https://unl-statistics.github.io/stat251/homework/06-data-manip.html"></iframe>
```

# The "Data"

- How much do you trust the data in this assignment?

- No? Good call! Something went terribly wrong in the data processing 

- Extra Credit: Assemble a data set from [gapminder](https://www.gapminder.org/data/) that contains the same/similar variables with corrected data. What went wrong with the data before?

# Next time

- Finish up on homework #6 assignment

