---
title: Dates and Times - and the script
author: Stat 251
date: 2026-04-9
categories:
- slides
- Week11
- Week12
engine: knitr
format:
  revealjs:
    navigation-mode: vertical
    logo: N.svg
    theme: inverse.scss
    includes:
      in_header: header.html
---


# Feedback

- Claimed Dataset: make sure to add the link to the Tidy Tuesday page

- Homework 10: Looks good, make sure to submit!



# Script

For each of the Things you defined, write out at least three paragraphs:

Make sure to:

  - include  definitions (i.e. how do you measure strength) 
  - give context (i.e. which variables are used)
  - tie 'things' in with the topics in the class


# Example Things

For the example of the repair cafes the things we might want to do are:  
  
  1. check where repair cafes originated 
  2. how did repair cafes do over time?
  3. which things are repaired and how successful are repairs?


# Where do repair cafes originate?

1. Definitions: Repair cafes are identified by `repair_cafe_number` and `repair_cafe_name`.
We will use the variable `country` to show where repair cafes are. We can measure 
origin for each cafe as the date of the first repair. 

2. What we do
  a. Data summary: For each repair cafe (group_by number and name) we create a summary of 
date of first repair (as the minimum of `repair_date`), date of last repair (maximum), number of total repairs, country.

# 

2. 
  b. Visual summary: To show the result we: map the first date of a repair for each cafe to the x axis, number of repairs on y and color by country and show as a scatterplot. Additionally,
we  add a line segment for each cafe's existence from first date to last date, and also color by country.

  c. Interpret the result and write summary.

3. React to potential problems

# Homework 11

Optional for extra credit

```{=html}
<iframe width="100%" height = "500px" src="https://unl-statistics.github.io/stat251/homework/11-functional-prog.qmd"></iframe>
```
